name: Fullstack CI/CD

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  # =========================
  # JOB BACKEND RAILS
  # =========================
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    services:
      db:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST: db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          sudo apt-get install -y libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          yarn install --check-files || true

      - name: Set up database
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Run RSpec tests
        run: bundle exec rspec

      - name: Run Cucumber tests
        run: bundle exec cucumber

      - name: Run Coveralls
        run: bundle exec coveralls

      - name: Run CodeClimate analysis
        uses: paambaati/codeclimate-action@v3.0.0
        with:
          coverageCommand: "bundle exec rspec"
          debug: true

  # =========================
  # JOB FRONTEND
  # =========================
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Run frontend tests
        run: yarn test

  # =========================
  # DEPLOY BACKEND HEROKU
  # =========================
  deploy_backend:
    needs: backend
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'nome-do-app'   # alguém crie pq n funciona pra mim :(
          heroku_email: 'seu-email@usp.br'
          app_dir: backend
